#!/usr/bin/env lua
-- KeyHints.lua - Interactive keybinding cheatsheet for Hyprland.
--
-- AUTO-GENERATED by installer/dev/gen_keyhints.py from
-- .config/hypr/modules/keybinds.lua. Do not edit by hand: re-run
-- the script to regenerate.
--
-- On launch, this script renders all bindings grouped by category
-- into a temporary file and pipes it into fzf. Pressing Enter on a
-- row copies the corresponding action string to the clipboard.

local shortcuts = {
  -- Category: Apps
  { "--- [Apps] ------------------------------------", "", "" },
  { "SUPER + B", "[Apps] Launch: firefox", "exec_cmd(\"firefox\")" },
  { "SUPER + E", "[Apps] Launch: kitty -e yazi", "exec_cmd(\"kitty -e yazi\")" },
  { "SUPER + Return", "[Apps] Launch: kitty", "exec_cmd(\"kitty\")" },
  { "SUPER + SHIFT + E", "[Apps] Launch: thunar", "exec_cmd(\"thunar\")" },
  { "SUPER + T", "[Apps] Launch: kitty", "exec_cmd(\"kitty\")" },
  -- Category: Layout
  { "--- [Layout] ----------------------------------", "", "" },
  { "SUPER + M", "[Layout] Layout / column control", "layout(\"fit active\")" },
  { "SUPER + R", "[Layout] Layout / column control", "layout(\"colresize +conf\")" },
  { "SUPER + SHIFT + R", "[Layout] Layout / column control", "layout(\"colresize -conf\")" },
  { "SUPER + SHIFT + comma", "[Layout] Layout / column control", "layout(\"swapprev\")" },
  { "SUPER + SHIFT + period", "[Layout] Layout / column control", "layout(\"swapnext\")" },
  { "SUPER + comma", "[Layout] Layout / column control", "layout(\"-col\")" },
  { "SUPER + period", "[Layout] Layout / column control", "layout(\"+col\")" },
  -- Category: Media
  { "--- [Media] -----------------------------------", "", "" },
  { "XF86AudioLowerVolume", "[Media] Media key", "exec_cmd(\"noctalia msg volume-down\")" },
  { "XF86AudioMicMute", "[Media] Media key", "exec_cmd(\"noctalia msg mic-mute\")" },
  { "XF86AudioMute", "[Media] Media key", "exec_cmd(\"noctalia msg volume-mute\")" },
  { "XF86AudioNext", "[Media] Media key", "exec_cmd(\"noctalia msg media next\")" },
  { "XF86AudioPause", "[Media] Media key", "exec_cmd(\"noctalia msg media toggle\")" },
  { "XF86AudioPlay", "[Media] Media key", "exec_cmd(\"noctalia msg media toggle\")" },
  { "XF86AudioPrev", "[Media] Media key", "exec_cmd(\"noctalia msg media previous\")" },
  { "XF86AudioRaiseVolume", "[Media] Media key", "exec_cmd(\"noctalia msg volume-up\")" },
  { "XF86AudioStop", "[Media] Media key", "exec_cmd(\"noctalia msg media stop\")" },
  { "XF86MediaPlayPause", "[Media] Media key", "exec_cmd(\"noctalia msg media toggle\")" },
  { "XF86MonBrightnessDown", "[Media] Brightness control", "exec_cmd(\"noctalia msg brightness-down\")" },
  { "XF86MonBrightnessUp", "[Media] Brightness control", "exec_cmd(\"noctalia msg brightness-up\")" },
  -- Category: Noctalia
  { "--- [Noctalia] --------------------------------", "", "" },
  { "ALT + Print", "[Noctalia] Noctalia shell command: screenshot-fullscreen pick", "exec_cmd(\"noctalia msg screenshot-fullscreen pick\")" },
  { "CTRL + ALT + L", "[Noctalia] Noctalia shell command: session lock", "exec_cmd(\"noctalia msg session lock\")" },
  { "CTRL + SUPER + Space", "[Noctalia] Noctalia shell command: media toggle", "exec_cmd(\"noctalia msg media toggle\")" },
  { "Print", "[Noctalia] Noctalia shell command: screenshot-fullscreen", "exec_cmd(\"noctalia msg screenshot-fullscreen\")" },
  { "SUPER + ALT + N", "[Noctalia] Noctalia shell command: media next", "exec_cmd(\"noctalia msg media next\")" },
  { "SUPER + ALT + P", "[Noctalia] Noctalia shell command: media previous", "exec_cmd(\"noctalia msg media previous\")" },
  { "SUPER + D", "[Noctalia] Noctalia shell command: panel-toggle launcher", "exec_cmd(\"noctalia msg panel-toggle launcher\")" },
  { "SUPER + I", "[Noctalia] Noctalia shell command: settings-toggle", "exec_cmd(\"noctalia msg settings-toggle\")" },
  { "SUPER + N", "[Noctalia] Noctalia shell command: nightlight-toggle", "exec_cmd(\"noctalia msg nightlight-toggle\")" },
  { "SUPER + P", "[Noctalia] Noctalia shell command: panel-toggle control-center", "exec_cmd(\"noctalia msg panel-toggle control-center\")" },
  { "SUPER + Print", "[Noctalia] Noctalia shell command: screenshot-fullscreen", "exec_cmd(\"noctalia msg screenshot-fullscreen\")" },
  { "SUPER + SHIFT + M", "[Noctalia] Noctalia shell command: mic-mute", "exec_cmd(\"noctalia msg mic-mute\")" },
  { "SUPER + SHIFT + N", "[Noctalia] Noctalia shell command: panel-toggle control-center notifications", "exec_cmd(\"noctalia msg panel-toggle control-center notifications\")" },
  { "SUPER + SHIFT + P", "[Noctalia] Noctalia shell command: panel-toggle session", "exec_cmd(\"noctalia msg panel-toggle session\")" },
  { "SUPER + SHIFT + Print", "[Noctalia] Noctalia shell command: screenshot-region", "exec_cmd(\"noctalia msg screenshot-region\")" },
  { "SUPER + SHIFT + W", "[Noctalia] Noctalia shell command: theme-mode-toggle", "exec_cmd(\"noctalia msg theme-mode-toggle\")" },
  { "SUPER + V", "[Noctalia] Noctalia shell command: panel-toggle clipboard", "exec_cmd(\"noctalia msg panel-toggle clipboard\")" },
  { "SUPER + W", "[Noctalia] Noctalia shell command: wallpaper-random", "exec_cmd(\"noctalia msg wallpaper-random\")" },
  { "SUPER + Y", "[Noctalia] Noctalia shell command: caffeine-toggle", "exec_cmd(\"noctalia msg caffeine-toggle\")" },
  -- Category: Overview
  { "--- [Overview] --------------------------------", "", "" },
  { "ALT + Tab", "[Overview] Workspace overview", "open_overview" },
  { "SUPER + Tab", "[Overview] Workspace overview", "open_overview" },
  { "down", "[Overview] Workspace overview", "if hl.plugin and hl.plugin.scrolloverview then hl.plugin.scrolloverview.navigate(\"down\")" },
  { "escape", "[Overview] Workspace overview", "close_overview" },
  { "h", "[Overview] Workspace overview", "if hl.plugin and hl.plugin.scrolloverview then hl.plugin.scrolloverview.navigate(\"left\")" },
  { "j", "[Overview] Workspace overview", "if hl.plugin and hl.plugin.scrolloverview then hl.plugin.scrolloverview.navigate(\"down\")" },
  { "k", "[Overview] Workspace overview", "if hl.plugin and hl.plugin.scrolloverview then hl.plugin.scrolloverview.navigate(\"up\")" },
  { "l", "[Overview] Workspace overview", "if hl.plugin and hl.plugin.scrolloverview then hl.plugin.scrolloverview.navigate(\"right\")" },
  { "left", "[Overview] Workspace overview", "if hl.plugin and hl.plugin.scrolloverview then hl.plugin.scrolloverview.navigate(\"left\")" },
  { "mouse:272", "[Overview] Workspace overview", "if hl.plugin and hl.plugin.scrolloverview then hl.plugin.scrolloverview.overview(\"select\") hl.plugin.scrolloverview.window(\"select\") hl.plugin.scrolloverview.overview(\"off\")" },
  { "mouse:274", "[Overview] Workspace overview", "if hl.plugin and hl.plugin.scrolloverview then hl.plugin.scrolloverview.window(\"close\")" },
  { "mouse_down", "[Overview] Workspace overview", "if hl.plugin and hl.plugin.scrolloverview then hl.plugin.scrolloverview.navigate(\"right\")" },
  { "mouse_up", "[Overview] Workspace overview", "if hl.plugin and hl.plugin.scrolloverview then hl.plugin.scrolloverview.navigate(\"left\")" },
  { "return", "[Overview] Workspace overview", "if hl.plugin and hl.plugin.scrolloverview then hl.plugin.scrolloverview.overview(\"select\")" },
  { "right", "[Overview] Workspace overview", "if hl.plugin and hl.plugin.scrolloverview then hl.plugin.scrolloverview.navigate(\"right\")" },
  { "up", "[Overview] Workspace overview", "if hl.plugin and hl.plugin.scrolloverview then hl.plugin.scrolloverview.navigate(\"up\")" },
  -- Category: Scratchpads
  { "--- [Scratchpads] -----------------------------", "", "" },
  { "SUPER + F1", "[Scratchpads] Scratchpad (btop-scratch): kitty --class btop-scratch -e btop", "toggle_scratchpad(\"btop-scratch\", \"kitty --class btop-scratch -e btop\")" },
  { "SUPER + SHIFT + Return", "[Scratchpads] Scratchpad (kitty-drop): kitty --class kitty-drop", "toggle_scratchpad(\"kitty-drop\", \"kitty --class kitty-drop\")" },
  { "SUPER + SHIFT + T", "[Scratchpads] Scratchpad (kitty-drop): kitty --class kitty-drop", "toggle_scratchpad(\"kitty-drop\", \"kitty --class kitty-drop\")" },
  { "SUPER + Slash", "[Scratchpads] Scratchpad (keyhints-scratch): kitty --class keyhints-scratch -e ~/.config/hypr/scripts/KeyHints.lua", "toggle_scratchpad(\"keyhints-scratch\", \"kitty --class keyhints-scratch -e ~/.config/hypr/scripts/KeyHints.lua\")" },
  -- Category: Windows
  { "--- [Windows] ---------------------------------", "", "" },
  { "ALT + F4", "[Windows] Force-close window (AltF4 helper)", "exec_cmd(\"~/.config/hypr/scripts/AltF4.lua\")" },
  { "CTRL + ALT + Down", "[Windows] Window management", "window.resize({ x = 0,  y = 100, relative = true })" },
  { "CTRL + ALT + Left", "[Windows] Window management", "window.resize({ x = -100, y = 0, relative = true })" },
  { "CTRL + ALT + Right", "[Windows] Window management", "window.resize({ x = 100,  y = 0, relative = true })" },
  { "CTRL + ALT + Up", "[Windows] Window management", "window.resize({ x = 0,  y = -100, relative = true })" },
  { "SUPER + 0", "[Windows] Window management", "focus({ workspace = 10 })" },
  { "SUPER + ALT + H", "[Windows] Window management", "group.prev()" },
  { "SUPER + ALT + L", "[Windows] Window management", "group.next()" },
  { "SUPER + ALT + Space", "[Windows] Window management", "window.pin({ action = \"toggle\" })" },
  { "SUPER + C", "[Windows] Window management", "window.center()" },
  { "SUPER + F", "[Windows] Window management", "window.fullscreen()" },
  { "SUPER + G", "[Windows] Window management", "group.toggle()" },
  { "SUPER + H", "[Windows] Window management", "focus({ direction = \"left\" })" },
  { "SUPER + J", "[Windows] Window management", "focus({ workspace = \"e+1\" })" },
  { "SUPER + K", "[Windows] Window management", "focus({ workspace = \"e-1\" })" },
  { "SUPER + L", "[Windows] Window management", "focus({ direction = \"right\" })" },
  { "SUPER + Q", "[Windows] Window management", "window.close()" },
  { "SUPER + SHIFT + 0", "[Windows] Window management", "window.move({ workspace = 10 })" },
  { "SUPER + SHIFT + D", "[Windows] Window info popup", "exec_cmd(\"~/.config/hypr/scripts/WindowInfo.lua\")" },
  { "SUPER + SHIFT + H", "[Windows] Window management", "window.move({ direction = \"left\" })" },
  { "SUPER + SHIFT + J", "[Windows] Window management", "window.move({ workspace = \"e+1\" })" },
  { "SUPER + SHIFT + K", "[Windows] Window management", "window.move({ workspace = \"e-1\" })" },
  { "SUPER + SHIFT + L", "[Windows] Window management", "window.move({ direction = \"right\" })" },
  { "SUPER + SHIFT + Tab", "[Windows] Window management", "focus({ workspace = \"e-1\" })" },
  { "SUPER + SHIFT + [1-9]", "[Windows] Window management", "window.move({ workspace = <1..9> })" },
  { "SUPER + SHIFT + mouse_down", "[Windows] Window management", "window.move({ workspace = \"e-1\" })" },
  { "SUPER + SHIFT + mouse_up", "[Windows] Window management", "window.move({ workspace = \"e+1\" })" },
  { "SUPER + Space", "[Windows] Window management", "window.float({ action = \"toggle\" })" },
  { "SUPER + [1-9]", "[Windows] Window management", "focus({ workspace = <1..9> })" },
  { "SUPER + mouse:272", "[Windows] Window management", "window.drag()" },
  { "SUPER + mouse:273", "[Windows] Window management", "window.resize()" },
  { "SUPER + mouse_down", "[Windows] Window management", "focus({ workspace = \"e-1\" })" },
  { "SUPER + mouse_up", "[Windows] Window management", "focus({ workspace = \"e+1\" })" },
}

local w1 = 0
for _, item in ipairs(shortcuts) do
    if item[2] ~= "" then
        w1 = math.max(w1, #item[1])
    end
end

local lines = {}
local map_action = {}
for _, item in ipairs(shortcuts) do
    local formatted
    if item[2] == "" then
        formatted = item[1]
    else
        formatted = string.format("%-" .. (w1 + 4) .. "s   %s", item[1], item[2])
    end
    table.insert(lines, formatted)
    map_action[formatted] = item[3]
end

local input_str = table.concat(lines, "\n")
local tmp_file = os.tmpname()
local f = io.open(tmp_file, "w")
if f then
    f:write(input_str)
    f:close()
end

local fzf_cmd = 'fzf --no-sort --cycle --header=" [ ENTER: Copy action to clipboard | ESC: Exit ]" --layout=reverse --border=rounded --prompt=" Search or browse by category: "'
local handle = io.popen(string.format("cat %s | %s", tmp_file, fzf_cmd))
local selected = handle:read("*l")
handle:close()
os.remove(tmp_file)

if selected and selected ~= "" then
    selected = selected:match("^%s*(.-)%s*$")
    local action = map_action[selected]
    if not action then
        action = selected:match(".*%s+([^\n]+)$")
    end
    if action then
        local copy_cmd = string.format("printf '%%s' %q | wl-copy", action)
        os.execute(copy_cmd)
        os.execute(string.format('notify-send "Shortcut Copied" "Action \'%s\' copied to clipboard!" -t 2000 -i edit-copy', action))
    end
end
