# Pacotes AUR instalados via yay

[[packages]]
name = "noctalia-git"
description = "Noctalia V5 shell"
rebuild_on_update = true

[[packages]]
name = "noctalia-greeter-git"
description = "Noctalia V5 greeter"
rebuild_on_update = true

[[packages]]
name = "bibata-cursor-theme-bin"
description = "Bibata cursor theme (binario pre-construido do AUR)"
rebuild_on_update = false

[[packages]]
name = "vesktop"
description = "Discord client"
rebuild_on_update = false

[[packages]]
name = "protonup-qt"
description = "Proton GE installer"
tags = ["gaming"]
rebuild_on_update = false
