# Pacotes Flatpak instalados via flatpak

[remote]
name = "flathub"
url = "https://dl.flathub.org/repo/flathub.flatpakrepo"

[[packages]]
name = "com.github.wwmm.easyeffects"
description = "PipeWire audio effects"
