[bar.default]
center = [ "wallpaper", "clock", "clipboard" ]
contact_shadow = true
end = [
    "media",
    "tray",
    "notifications",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "control-center",
    "session"
]
margin_edge = 5
radius = 14
shadow = true
start = [ "launcher", "workspaces" ]

[dock]
active_monitor_only = true
shadow = true

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 961.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[shell]
lang = "pt-BR"
launch_apps_as_systemd_services = true
polkit_agent = true
telemetry_enabled = true

    [shell.greeter_sync]
    auto_sync = true

    [shell.launcher]
    categories = false
    compact = true

    [shell.panel]
    control_center_placement = "attached"
    session_placement = "attached"
    shadow = true
    wallpaper_placement = "attached"

    [shell.screen_corners]
    enabled = true

    [shell.screenshot]
    confirm_region = true
    directory = "/home/gabrln/Pictures/Screenshots"
    pipe_to_command = true

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    label = "Suspender"
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[templates.nvim-base16]
input_path = "~/.config/nvim/lua/matugen-template.lua"
output_path = "~/.config/nvim/lua/matugen.lua"
post_hook = "pkill -SIGUSR1 nvim"

[theme]
builtin = "Eldritch"
community_palette = "GitHub Dark"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "kitty", "mango", "niri", "qt", "starship" ]
    community_ids = [ "pywalfox", "neovim", "discord" ]

[wallpaper.default]
path = "/home/gabrln/Pictures/Wallpapers/083.jpg"

[wallpaper.last]
path = "/home/gabrln/Pictures/Wallpapers/083.jpg"

[wallpaper.monitors.eDP-1]
path = "/home/gabrln/Pictures/Wallpapers/083.jpg"

[widget.network]
show_label = false

[widget.tray]
detached_panel = true
drawer = true
pinned = [ "Shelly" ]
